Repository 0xPolygon/wiki, pull requests merged in 2023-07, with the labels that each got.

#14 feat(wiki): upgrade dependencies
  yarn.lock
Labels: dependencies

#15 update(supernets): aws ssm key generation example
  docs/supernets/operate/deploy/local-supernet.md
Labels: pos:supernets, type:enhancement

#17 feature: erigon snapshot support
  docs/pos/reference/snapshot-instructions-heimdall-bor.md
Labels: pos:mainnet, type:enhancement

#23 feat(supernets): v1.1 release documentation
  docs/supernets/operate/deploy/upgrades/hardfork.md
  docs/supernets/operate/deploy/upgrades/v1.1.md
  docs/supernets/operate/install.md
  sidebars.js
Labels: type:new

#19 feat(PoS): add frequently used node commands
  docs/pos/operate/frequent-node-commands.md
  sidebars.js
Labels: pos:mainnet, type:new

#28 update(wiki): enh to legal material
  CONTENT_DISCLAIMER.md
  docusaurus.config.js
Labels: P1, type:enhancement

#30 feat(PoS): add heimdall fee topup document
  docs/pos/operate/validator/topup-heimdall-fee.md
  sidebars.js
  static/img/connect-wallet-etherscan.png
  static/img/topup-heimdall-fee.png
Labels: area:validate, need:sme
