Repository 0xPolygon/wiki, pull requests merged in 2023-08, with the labels that each got.

#29 feat(supernets): bridge diagrams
  docs/supernets/get-started/what-are-supernets.md
  docs/supernets/operate/deploy/transfers/deposit.md
  docs/supernets/operate/deploy/transfers/withdraw.md
  static/img/supernets/bridge-deposit-childchain.excalidraw.png
  static/img/supernets/bridge-deposit-rootchain.excalidraw.png
  static/img/supernets/bridge-withdraw-childchain.excalidraw.png
  static/img/supernets/bridge-withdraw-rootchain.excalidraw.png
Labels: pos:supernets, type:enhancement

#31 update(supernets): premine field is mandatory
  docs/supernets/operate/deploy/genesis.md
Labels: need:review

#37 Update topup-heimdall-fee.md
  docs/pos/operate/validator/topup-heimdall-fee.md
Labels: pos:mainnet, type:footprint

#43 feature: 1-liner snapshot download/extract cmd
  docs/pos/reference/snapshot-instructions-heimdall-bor.md
Labels: pos:mainnet, type:enhancement

#46 fix(pos): markdown syntax after recent snapshot instructions update
  docs/pos/reference/snapshot-instructions-heimdall-bor.md
  package.json
  yarn.lock
Labels: type:footprint

#47 Corrections on md files
  docs/miden/user_docs/usage.md
  docs/pos/faqs.md
  docs/pos/operate/node/full-node-deployment.md
  docs/pos/operate/validator/change-signer-address.md
  docs/pos/operate/validator/issues/reporting-issues.md
  docs/pos/operate/validator/move-stake.md
  docs/pos/operate/validator/technical-faqs.md
  docs/pos/reference/mapped-tokens.md
Labels: type:footprint

#50 Fixes issue #42
  docs/pos/design/bridge/l1-l2-communication/fx-portal.md
  docs/pos/design/bridge/l1-l2-communication/fx-portal/example.md
Labels: type:footprint

#51 fix(pos): graphql server ports
  docs/pos/reference/port_management.md
Labels: pos:mainnet, type:footprint

#52 feat(PoS): add bloxroute to the Wiki
  docs/pos/operate/validator/bloxroute.md
  sidebars.js
Labels: area:validate, type:footprint

#49 chore: add tips for debug namespace
  docs/supernets/api/json-rpc-debug.md
Labels: pos:supernets, type:enhancement

#56 Add SmartPress to contract create options
  docs/pos/deploy/smartpress.md
  sidebars.js
Labels: pos:mainnet, type:new

#61 Fix/texts
  docs/pos/deploy/smartpress.md
  docs/supernets/design/bridge/overview.md
  docs/supernets/design/grpc.md
  docs/supernets/operate/quick-start.md
  docs/tools/oracles/optimisticoracle.md
Labels: type:footprint

#63 feat(zkEVM): update bridge document
  docs/zkevm/bridge-to-zkevm.md
Labels: need:review, zk:zkevm

#64 fix typos
  docs/pos/design/validator/core-components/heimdall-chain.md
  docs/zkevm/zkProver/binary-sm.md
  docs/zkevm/zkProver/intro-main-sm.md
  docs/zkevm/zkProver/mfibonacci-example.md
  docs/zkevm/zkProver/pil-stark.md
  docs/zkevm/zkProver/proving-setup-phase.md
  docs/zkevm/zkProver/verification-scheme.md
Labels: type:footprint

#66 chore(wiki): update staging deployment - temp
  .github/workflows/staging_deployment.yml
Labels: type:chore

#67 chore(wiki): update prod deployment
  .github/workflows/prod_deployment.yml
Labels: type:chore

#71 Updated content and screenshots for 'How to Delegate' page
  docs/delegate/delegate.md
  static/img/staking/home.png
  static/img/staking/move.png
  static/img/staking/move2.png
  static/img/staking/restake-rewards.png
  static/img/staking/unbond-from-validator.png
  static/img/staking/unbond-from-validator2.png
  static/img/staking/unbond.png
  static/img/staking/withdraw-reward.png
Labels: need:review, pos:mainnet, type:enhancement

#75 feat(wiki): fix broken link on landing page
  src/data/features.js
Labels: bug, need:review

#69 Add Chainbase as endpoint rpc provider
  docs/pos/reference/rpc-endpoints.md
Labels: ext:infra, type:footprint

#65 Corrected rootchain deploy command
  docs/supernets/operate/deploy/rootchain-config.md
Labels: pos:supernets, type:footprint

#62 feat(PoS): update validator set up guide
  docs/pos/operate/validator/run-validator.md
Labels: area:validate, need:sme

#78 Updates screenshots and outdated content on Delegator FAQ page
  docs/delegate/delegator-faq.md
  static/img/delegator-faq/my-account.png
  static/img/delegator-faq/supported-wallet.png
  static/img/delegator-faq/withdraw-reward.png
  static/img/staking/supported-wallet.png
Labels: need:review

#82 update(wiki): revamp readme
  README.md
  docs/contribute/community-maintainers.md
  sidebars.js
  static/img/readme/cdk-zk-flow.png
  static/img/readme/polygon2.0-governance-pillars.png
  static/img/readme/polygon2.0-layers-1.png
  static/img/readme/polygon2.0-layers.png
Labels: do not merge, need:review, need:sme, type:enhancement

#83 update(wiki): rmv gaming from navbar
  docusaurus.config.js
Labels: type:footprint

#84 Update rpc-endpoints.md
  docs/pos/reference/rpc-endpoints.md
Labels: type:chore

#77 404 Fix
  docusaurus.config.js
Labels: type:footprint

#88 update(cdk): follow-up-2 updates for initial docs
  README.md
  docs/cdk/dac.md
  docs/cdk/deployment-differences.md
  docs/cdk/what-is-polygon-cdk.md
Labels: type:enhancement, cdk

#89 update(cdk): follow-up-3 updates for initial docs
  README.md
  docs/cdk/deployment-differences.md
  docs/cdk/quickstart.md
  docs/cdk/what-is-polygon-cdk.md
  static/img/cdk/cdk-stack.excalidraw.png
Labels: do not merge, need:review, type:footprint, cdk

#90 update(cdk): follow-up-4 updates for initial docs
  docs/cdk/deployment-differences.md
Labels: type:footprint, cdk

#86 Added /docs/tools/data/parsiq.md
  docs/tools/data/parsiq.md
  sidebars.js
Labels: ext:data, type:new

#92 Update faqs.md
  docs/pos/faqs.md
Labels: pos:mainnet, type:enhancement

#93 md files
  README.md
  docs/tools/oracles/api3.md
Labels: type:footprint
